# hello-whale-chart/values.yaml
replicaCount: 1

image:
  repository: flask-whale-app
  tag: v1
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8089

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

namespace: flask-whale-app

ingress:
  enabled: false  # Set to true to enable ingress
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []  # Define TLS settings here if needed 

