{{- if .Values.agents.useConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agents-useConfigMap-configmap-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
  annotations:
    {{- if .Values.agents.customAgentConfig }}
    checksum/agent-config: {{ tpl (toYaml .Values.agents.customAgentConfig) . | sha256sum }}
    {{- end }}
data:
  datadog.yaml: |
  {{- if .Values.agents.customAgentConfig }}
{{ tpl (toYaml .Values.agents.customAgentConfig) . | indent 4 }}
  {{- else }}
    ## Provides autodetected defaults, for kubernetes environments,
    ## please see datadog.yaml.example for all supported options

    # Custom configuration for Datadog agents

    apm_config:
      apm_non_local_traffic: true
    
    # Enable container support for Java Management Extensions (JMX)
    jmx_use_container_support: true

    # Enable logs collection and configure file and container log sources
    logs_enabled: true
    logs:
      # - type: file
      #   path: /app/logs/prime_number.log
      #   service: prime_number_app
      #   source: python
      - type: container
        path: /var/log/containers/*.log
        service: kube-logs
        source: kubernetes
      - type: file
        path: /app/logs/hello_whale.log
        service: hello_whale
        source: python
    
    # Configure listeners and config providers for Docker
    listeners:
      - name: docker
    config_providers:
      - name: docker
        polling: true
    
    # Enable container log collection
    logs_config:
      container_collect_all: true

    # Enable process collection
    process_config:
      process_collection:
        enabled: true

    # Enable system probe
    system_probe_config:
      enabled: true

    # Datadog's log forwarding feature is configured to work with Splunk
    # log_forwarding:
    #   splunk:
    #     host: "https://localhost:8088"
    #     port: 8088
    #     token: "d7fb1a06-5ae5-4461-b6ff-233bb7212d89"
    #     index: main
    
    # Datadog site configuration
    site: datadoghq.eu

    {{- $version := (.Values.agents.image.tag | toString | trimSuffix "-jmx") }}
    {{- $length := len (split "." $version ) -}} 
    {{- if and (eq $length 1) (ge $version "6") -}}
    {{- $version := "6.15" }}  
    {{- end -}}
    {{ if semverCompare ">=6.15" $version }}
    # Enable java container awareness (agent version >= 6.15)
    jmx_use_container_support: true
    {{ else }}
    # Enable java cgroup memory awareness (agent version < 6.15)
    jmx_use_cgroup_memory_limit: true
    {{ end }}
  {{- end }}
{{- end }}
