name: Docker Build and Publish

on:
  push:
    branches: [ "NOK-003/Deployment" ]

env:
  REGISTRY: 583.dkr.ecr.eu-west-2.amazonaws.com/hello-whale
  IMAGE_NAME: flask-app

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container  # Ensure Buildx uses the Docker container driver

      # Step 3: Log in to AWS ECR
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker buildx build --platform linux/amd64 -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA -f app/Dockerfile app --push

      # Note: No need for a separate push step since it's already handled in the build step.
